### ISSUE TITLE
Exception in moreunit decorator

### ISSUE THREAD

**Issue by Bananeweizen** [MoreUnit/MoreUnit-Eclipse#81]
The moreunit decorator just got disabled in my installation due to this exception in the decorator. It would probably be sufficient to just have a try-catch-all around the JDT code in moreunit here.

```
java.lang.IndexOutOfBoundsException: start 1804, end 10273, length 10268
	at java.base/java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1716)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:685)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:228)
	at org.eclipse.jface.text.GapTextStore.get(GapTextStore.java:164)
	at org.eclipse.jface.text.CopyOnWriteTextStore.get(CopyOnWriteTextStore.java:128)
	at org.eclipse.jface.text.AbstractDocument.get(AbstractDocument.java:961)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.get(SynchronizableDocument.java:116)
	at org.eclipse.jdt.internal.ui.javaeditor.DocumentAdapter.getContents(DocumentAdapter.java:419)
	at org.eclipse.jdt.internal.ui.javaeditor.DocumentAdapter.getCharacters(DocumentAdapter.java:410)
	at org.eclipse.jdt.internal.core.CompilationUnit.getContents(CompilationUnit.java:689)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator$WorkingCopyDocument.<init>(MatchLocator.java:181)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.workingCopiesThatCanSeeFocus(MatchLocator.java:248)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.addWorkingCopies(MatchLocator.java:201)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:249)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:595)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.moreunit.util.SearchTools.search(SearchTools.java:44)
	at org.moreunit.util.SearchTools.searchFor(SearchTools.java:36)
	at org.moreunit.matching.CorrespondingTypeSearcher.findPotentialTargets(CorrespondingTypeSearcher.java:73)
	at org.moreunit.matching.CorrespondingTypeSearcher.getMatches(CorrespondingTypeSearcher.java:57)
	at org.moreunit.elements.TypeFacade.getCorrespondingClasses(TypeFacade.java:207)
	at org.moreunit.elements.ClassTypeFacade.getCorrespondingTestCases(ClassTypeFacade.java:78)
	at org.moreunit.elements.ClassTypeFacade.hasTestCase(ClassTypeFacade.java:179)
	at org.moreunit.decorator.UnitDecorator.decorate(UnitDecorator.java:54)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:247)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:360)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:346)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:386)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:362)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by apupier** [comment]
@Bananeweizen thanks for the report.
Can you precise which version of Eclipse and MoreUnit you are using please?
If I understand correctly, it doesn't happen everytime?

At first sight, it smells the bug in JDT, i would prefer that we can fix it in JDT than to put arbitrary try catch.

**Comment by Bananeweizen** [comment]
This doesn't happen all the time, but very seldom only. I don't think there is a bug in JDT per se. Issues like this occur if files are modified all the time while a build is running (e.g. doing mass refactorings, regenerating Xtend code etc.), since JDT does not lock all the resources it is dealing with. I believe that JDT may internally experience the same kind of exception, but just catches it and continues. Therefore to me the only thing needed here is hardening moreunit to cope with this situation. (Similarly I recently raised a bug where Sonarlint had an index out of bounds exception, because the scanned file was modified in the short time frame between analyzing it and trying to set error markers).

Eclipse is 2019-09. Have to check for the moreunit version when at work (but should be most recent released version, since I use both Oomph updates as well as automatic P2 updates in all installations).

**Comment by maherm** [comment]
I have a similar problem using Eclipse 2019-12.
It occurs  non-deterministically in the middle of building a multimodule maven project. I believe the fix @Bananeweizen proposed is the right way.

```
!ENTRY org.eclipse.core.jobs 4 2 2021-06-30 12:04:45.170
!MESSAGE An internal error occurred during: "Decoration Calculation".
!STACK 0
java.util.zip.ZipError: jzentry == 0,
 jzfile = 1316986064,
 total = 495,
 name = {path to internal SNAPTSHOT dependency},
 i = 1,
 message = null
    at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:534)
    at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
    at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
    at org.eclipse.jdt.internal.core.builder.ClasspathJar.readJarContent(ClasspathJar.java:100)
    at org.eclipse.jdt.internal.core.builder.ClasspathJar.findPackageSet(ClasspathJar.java:93)
    at org.eclipse.jdt.internal.core.builder.ClasspathJar.scanContent(ClasspathJar.java:350)
    at org.eclipse.jdt.internal.core.builder.ClasspathJar.isPackage(ClasspathJar.java:322)
    at org.eclipse.jdt.internal.core.builder.ClasspathJar.findClass(ClasspathJar.java:262)
    at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.findClass(JavaSearchNameEnvironment.java:276)
    at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.findType(JavaSearchNameEnvironment.java:311)
    at org.eclipse.jdt.internal.compiler.env.IModuleAwareNameEnvironment.findType(IModuleAwareNameEnvironment.java:101)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createPlainPackage(LookupEnvironment.java:1137)
    at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildTypeBindings(CompilationUnitScope.java:135)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:473)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.parseAndBuildBindings(MatchLocator.java:1921)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1272)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1373)
    at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1492)
    at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:112)
    at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:250)
    at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:595)
    at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
    at org.moreunit.util.SearchTools.search(SearchTools.java:44)
    at org.moreunit.util.SearchTools.searchFor(SearchTools.java:36)
    at org.moreunit.matching.CorrespondingTypeSearcher.findPotentialTargets(CorrespondingTypeSearcher.java:73)
    at org.moreunit.matching.CorrespondingTypeSearcher.getMatches(CorrespondingTypeSearcher.java:57)
    at org.moreunit.elements.TypeFacade.getCorrespondingClasses(TypeFacade.java:207)
    at org.moreunit.elements.ClassTypeFacade.getCorrespondingTestCases(ClassTypeFacade.java:78)
    at org.moreunit.elements.ClassTypeFacade.hasTestCase(ClassTypeFacade.java:179)
    at org.moreunit.decorator.UnitDecorator.decorate(UnitDecorator.java:54)
    at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:247)
    at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:360)
    at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:346)
    at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:386)
    at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:362)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
