### ISSUE TITLE
Exception when CTRL+J in Eclipse 2021-06

### ISSUE THREAD

**Issue by nmahoude** [MoreUnit/MoreUnit-Eclipse#97]
Hi,
I'm on Eclipse  2021-06 (Not Released yet) and I have an exception when hitting CTRL+J .
I think there was an incompatible change in JDT API. 

**Error calling extension: org.moreunit.handler.Jumper.jump()**

```
java.lang.NoSuchMethodError: 'void org.eclipse.jdt.internal.junit.wizards.MethodStubsSelectionButtonGroup.<init>(int, java.lang.String[], int)'
	at org.moreunit.wizards.MoreUnitWizardPageOne.<init>(MoreUnitWizardPageOne.java:165)
	at org.moreunit.wizards.NewTestCaseWizard.addPages(NewTestCaseWizard.java:51)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:632)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.moreunit.wizards.NewClassyWizard.open(NewClassyWizard.java:40)
	at org.moreunit.elements.TypeFacade$OpenNewClassWizard.getCorrespondingMember(TypeFacade.java:320)
	at org.moreunit.elements.TypeFacade.getOneCorrespondingMember(TypeFacade.java:130)
	at org.moreunit.handler.JumpActionExecutor.executeJumpAction(JumpActionExecutor.java:106)
	at org.moreunit.handler.JumpActionExecutor.executeJumpAction(JumpActionExecutor.java:80)
	at org.moreunit.handler.Jumper.jump(Jumper.java:14)
	at org.moreunit.core.extension.JumperExtensionManager$1.run(JumperExtensionManager.java:38)
	at org.moreunit.core.extension.JumperExtensionManager$1.run(JumperExtensionManager.java:1)
	at org.moreunit.core.util.ExtendedSafeRunner$GenericRunnable.doRun(ExtendedSafeRunner.java:21)
	at org.moreunit.core.util.ExtendedSafeRunner$GenericRunnable.access$0(ExtendedSafeRunner.java:19)
	at org.moreunit.core.util.ExtendedSafeRunner$SafeRunnable.run(ExtendedSafeRunner.java:64)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.moreunit.core.util.ExtendedSafeRunner.run(ExtendedSafeRunner.java:43)
	at org.moreunit.core.util.ExtendedSafeRunner.applyTo(ExtendedSafeRunner.java:27)
	at org.moreunit.core.extension.JumperExtensionManager.jump(JumperExtensionManager.java:26)
	at org.moreunit.core.commands.JumpActionExecutor.execute(JumpActionExecutor.java:33)
	at org.moreunit.core.commands.JumpActionExecutor.execute(JumpActionExecutor.java:22)
	at org.moreunit.core.commands.JumpActionHandler.execute(JumpActionHandler.java:16)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor225.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
```
More unit : 
3.2.0

Eclipse : 
eclipse.buildId=4.20.0.I20210526-2310
java.version=11.0.10
java.vendor=Microsoft
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/D:/workspaces/PPE-2021-03/ -product org.eclipse.epp.package.jee.product

**Comment by nmahoude** [comment]
It's back in the last update. Sorry

Eclipse version : 
Version: 4.20.0.v20210527-0259
Build id: I20210526-2310

**Comment by apupier** [comment]
Thank you very much for the alert even if it was finally back.

**Comment by nmahoude** [comment]
I'm really sorry, but the error is still here. It's ok when the Test file exists (JUMP works) but not when the test file does not exists.
To be sure I downloaded a fresh version of eclipse 2021-06 RC1 and only install moreunit plugin.

The stack trace is exactly the same as before.

eclipse.buildId=4.20.0.I20210526-2310
java.version=11.0.10
java.vendor=Microsoft
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product

**Comment by doggy-dev** [comment]
I'm using the Ctrl+J for creating new test classes. This is really an important feature for me. It would be nice if we get a fix for this.

**Comment by uwesinha** [comment]
Can confirm this issue for the 2021-06 release: 

eclipse.buildId=4.20.0.I20210611-1600
java.version=11.0.10
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product

The stacktrace is the same, no matter whether I'm calling "Jump to test method" or "Generate test method", or whether I'm using the context menu or the keyboard shortcuts (Ctrl-J/Ctrl-T). The error only occurs if the Test file does not exist (yet). 

For those googling the error log messages -- depending on how "jump"/"generate" was called, they vary between:

- _Unhandled event loop exception_ 
- _Error calling extension: org.moreunit.handler.Jumper.jump()_
- _Problems occurred when invoking code from plug-in: "org.moreunit.core"_

**Comment by megazone23** [comment]
I am seeing the same problem with the exact same stacktrace.

Version: 2021-06 (4.20.0)
Build id: 20210612-2011

**Comment by ingogriebsch** [comment]
I face the same problem. I'm using

Spring Tool Suite 4
Version: 4.11.0.RELEASE
Build Id: 202106180608

**Comment by gkfirst8** [comment]
I can also confim this. The 'fun' thing is that jumping back to the code-under-test DOES work without any exception.

Version: 2021-06 (4.20.0)
Build id: 20210612-2011

**Comment by loetscher** [comment]
eclipse.buildId=4.20.0.I20210611-1600
java.version=11.0.8
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_CH

Verified that a change in
`org.moreunit.wizards.MoreUnitWizardPageOne.MoreUnitWizardPageOne(NewTestCaseWizardPageTwo, ProjectPreferences, LanguageType)`
from `        fMethodStubsButtons = new MethodStubsSelectionButtonGroup(SWT.CHECK, buttonNames, 2);`
to `fMethodStubsButtons = new MethodStubsSelectionButtonGroup(SWT.CHECK, JUnitVersion.VERSION_4, 2);`
would fix the problem for Eclipse 2021-06.
